# Copyright 2021 Manna Harbour
# https://github.com/manna-harbour/miryoku

name: 'dactyl'
on:
  - workflow_dispatch
jobs:
  build:
    uses: ./.github/workflows/main.yml
    with:
      keyboard: '["handwired/dactyl_manuform/5x6"]'
