# Copyright 2021 Manna Harbour
# https://github.com/manna-harbour/miryoku

name: 'wylder'
on:
  - workflow_dispatch
jobs:
  build:
    uses: ./.github/workflows/main.yml
    with:
      keyboard: '["handwired/wylderbuilds/4x5"]'
